language: php
dist: jammy

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHPUNIT_FLAGS="-v"

jobs:
  fast_finish: true
  include:
    # Lowest-deps runs
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 8.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    # Stable-deps runs  
    - php: 7.4
    - php: 8.0
    - php: 8.1
    - php: 8.2
    - php: 8.3

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ -n "$STABILITY" ]]; then composer config minimum-stability ${STABILITY}; fi
  - if [[ -n "$DEPENDENCIES" ]]; then composer require --no-update ${DEPENDENCIES}; fi

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS
