language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email:
    - richard@vandenbrand.org

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
